config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'accueil#presentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Exemple utilisant uniquement le controlleur (Classe: BattleshipsControlleur, méthode: index_1)
  get '/exemple1' , to: 'exemple#index_1'

  # Exemple utilisant uniquement le controlleur et du JSON
  get '/exemple2' , to: 'exemple#index_2'

  # Exemple utilisant uniquement le controlleur et du XML
  get '/exemple3' , to: 'exemple#index_3'

  # Exemple utilisant les callbacks
  get '/exemple4' , to: 'exemple#index_4'

  # Exemple utilisant les mimetypes
  get '/exemple5' , to: 'exemple#index_5'

  # Exemple utilisant les mimetypes
  get '/exemple6' , to: 'exemple#index_6'

  # Exemple utilisant un parametre nommé "id", le ":" represente un espace réservé à un paramètre
  get '/exemple/:id', to: 'exemple#show_1', as: 'exemple_show' # Lorsque la route est ambigue par rapport aux autres, on defini un nom unique avec le as

  get '/exemple_template_1' , to: 'exemple_template#index_1'

  # Exemple utilisant uniquement le controlleur et du JSON
  get '/exemple_template_2' , to: 'exemple_template#index_2'

  # Exemple utilisant uniquement le controlleur et du XML
  get '/exemple_template_3' , to: 'exemple_template#index_3'

  # Exemple utilisant les callbacks
  get '/exemple_template_4' , to: 'exemple_template#index_4'

  # Exemple utilisant les mimetypes
  get '/exemple_template_5' , to: 'exemple_template#index_5'

  post '/exemple_template_post_5' , to: 'exemple_template#index_post_5'

  # Exemple utilisant les mimetypes
  get '/exemple_template_6' , to: 'exemple_template#index_6'
  post '/exemple_template_post_6' , to: 'exemple_template#index_post_6'

  # Exemple utilisant uniquement le controlleur (Classe: BattleshipsControlleur, méthode: index_1)
  get '/css1' , to: 'css#index_1'

  # Exemple utilisant uniquement le controlleur et du JSON
  get '/css2' , to: 'css#index_2'

  # Exemple utilisant uniquement le controlleur et du JSON
  get '/restricted' , to: 'restricted#index'

  namespace :admin do
    get '/users/:is_admin', to: 'users#index'
    get '/users', to: 'users#index'
  end
end

app/controllers/exemple_template_controller.rb
# CHAQUE ACTION SUIVI D'UN NUMERO EST A TITRE PEDAGOGIQUE SEULEMENT (ex. index_1)
# En tout temps, la méthode "byebug" peut être ajouté afin de stoper une requête et vérifier de l'information ou faire des tests.
class ExempleTemplateController < ApplicationController
  before_action :get_parties, except: [:index_5, :index_post_5, :index_6]

  #layout false

  # Exemple utilisant aucun layout
  def index_1

    respond_to do |format|
      format.html { render layout: false } # Voir le résultat dans le html généré sur chrome et comparer avec index_2
    end
  end


  # Exemple utilisant le layout par defaut (views/layouts/application.html.erb)
  def index_2

    # ces lignes sont sous-entendues
    #respond_to do |format|
    #  format.html
    #end
  end


  # Exemple utilisant un layout custom
  def index_3

    respond_to do |format|
      format.html { render layout: 'exemple1' }
    end
  end


  # Exemple utilisant un layout et une partiel en boucle
  # https://edgeguides.rubyonrails.org/layouts_and_rendering.html
  def index_4

  end

  # Exemple utilisant le un formulaire
  def index_5

  end

  # Exemple utilisant qui recois le formulaire
  def index_post_5
    @joueur = Joueur.new(nom: params[:nom], prenom: params[:prenom], email: params[:email])

    respond_to do |format|
      if @joueur.save # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
        format.html {redirect_to '/exemple_template_5'}
      else
        format.html # Si une erreur arrive, on l'affiche sur le formulaire
      end
    end
  end

  # exemple en utilisant les modèles
  def index_6
    @joueur = Joueur.new
  end

  def index_post_6
    joueur_params = params.require(:joueur).permit(:nom, :prenom, :email) # Securite lors d'une assignation de masse, on filtre les paramètres authoriser avant de les envoyer au modèle qui gère la base de données
    @joueur = Joueur.new(joueur_params)

    respond_to do |format|

      if @joueur.save # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
        format.html {redirect_to '/exemple_template_6'}
      else
        format.html {render 'index_6' } # Si une erreur arrive, on l'affiche sur le formulaire d'origine
      end
    end
  end

  # Exemple utilisant un css, et des assets
  def index_7

  end

  # Exemple utilisant un parametre
  # Notez bien que les paramêtres provenant de l'URL sont traités de la même façon que les paramêtre d'un formulaire
  # Via la méthode "params" qui retourne une table de hashage
  def show_1
    # Recherche dans la base de données
    @partie = Partie.find(params[:id])

    # Modélisation du texte à retourner au navigateur
    @joueurs = {joueur_1: @partie.joueur_1, joueur_2: @partie.joueur_2 }.as_json # Pour générer du xml, l'objet doit être sous forme d'un json

    # l'url répond au format demandé ex: /battleships5.json, /battleships5.xml...
    # Le traitement reste le même, seul le format de la réponse change
    respond_to do |format|
      format.html { render :html => @joueurs.to_s }
      format.json { render :json => @joueurs.to_json }
      format.xml { render :xml => @joueurs.to_xml }
    end
  end

  # Tout ce qui suis ce mot est déclaré comme private, par défaut tout est public (les actions plus haut)
  private

  # Methode utilisé dans plusieurs action du contrôleur
  def get_parties
    @parties = Partie.all
  end

end

app/views/exemple_template/_partie.html.erb
<h1>
  Partie id: <%= partie.id %> <br />
  <i><%= partie.status %></i>
  <!-- Un lien peut etre generer en relatif battleship_show_path (path) et absolue battleship_show_url (url) -->
  <%= link_to 'voir cette partie', exemple_show_path(id: partie.id) %>
</h1>
Joueur 1 :<%= partie.joueur_1.fullname %><br />
<% if partie.joueur_2 %>
  Joueur 2 :<%= partie.joueur_2.fullname %><br />
<% end %>

app/views/exemple_template/index_1.html.erb
Liste des joueurs <br />
<% @parties.each do |partie| %>
<h1>
    Partie id: <%= partie.id %> <br />
    <i><%= partie.status %></i>
    <% # Un lien peut etre generer en relatif battleship_show_path (path) et absolue battleship_show_url (url) %>
    <%= link_to 'voir cette partie', exemple_show_path(id: partie.id) %>
</h1>
Joueur 1 :<%= partie.joueur_1.fullname %><br />
<% if partie.joueur_2 %>
Joueur 2 :<%= partie.joueur_2.fullname %><br />
<% end %>
<% end %>

app/views/exemple_template/index_2.html.erb
Liste des joueurs <br />
<% @parties.each do |partie| %>
  <h1>
    Partie id: <%= partie.id %> <br />
    <i><%= partie.status %></i>
    <% # Un lien peut etre generer en relatif battleship_show_path (path) et absolue battleship_show_url (url) %>
    <%= link_to 'voir cette partie', exemple_show_path(id: partie.id) %>
  </h1>
  Joueur 1 :<%= partie.joueur_1.fullname %><br />
  <% if partie.joueur_2 %>
    Joueur 2 :<%= partie.joueur_2.fullname %><br />
  <% end %>
<% end %>

app/views/exemple_template/index_3.html.erb
Liste des joueurs <br />
<% @parties.each do |partie| %>
  <h1>
    Partie id: <%= partie.id %> <br />
    <i><%= partie.status %></i>
    <% # Un lien peut etre generer en relatif battleship_show_path (path) et absolue battleship_show_url (url) %>
    <%= link_to 'voir cette partie', exemple_show_path(id: partie.id) %>
  </h1>
  Joueur 1 :<%= partie.joueur_1.fullname %><br />
  <% if partie.joueur_2 %>
    Joueur 2 :<%= partie.joueur_2.fullname %><br />
  <% end %>
<% end %>

app/views/exemple_template/index_4.html.erb
Liste des joueurs <br />
<% @parties.each do |partie| %>
  <!-- une partiel débute toujours par un "_" dans le nom de fichier mais jamais dans le code --> 
  <%= render 'partie', {partie: partie}  %>
<% end %>

app/views/exemple_template/index_5.html.erb
<%= link_to 'documentation des formulaires', 'https://guides.rubyonrails.org/form_helpers.html', target: '_BLANK' %>
<br />

<% if @joueur %>
  <%= @joueur.errors %>
<% end %>

<%= form_with(url: "/exemple_template_post_5", method: "post") do %>
  <%= label_tag(:nom, "nom:") %>
  <br />
  <%= text_field_tag(:nom) %>
  <br />
  <%= label_tag(:prenom, "prenom:") %>
  <br />
  <%= text_field_tag(:prenom) %>
  <br/>
  <%= label_tag(:email, "email:") %>
  <br/>
  <%= email_field_tag(:email) %>
  <br />
  <%= submit_tag("Ajouter") %>
<% end %>

app/views/exemple_template/index_6.html.erb
<style>
  .field_with_errors {
    color: red;
  }
</style>

<%= link_to 'documentation des formulaires', 'https://guides.rubyonrails.org/form_helpers.html', target: '_BLANK' %>
<br />


<%= form_for(@joueur, url:'/exemple_template_post_6', method: "post") do |f| %>
  <%= f.label(:nom) %>
  <%= @joueur.errors[:nom].join('<br />') %>
  <br/>
  <%= f.text_field(:nom) %>
  <br />
  <%= f.label(:prenom) %>
  <%= @joueur.errors[:prenom].join('<br />') %>
  <br/>
  <%= f.text_field(:prenom) %>
  <br/>
  <%= f.label(:email) %>
  <%= @joueur.errors[:email].join('<br />') %>
  <br/>
  <%= f.email_field(:email) %>
  <br />
  <%= submit_tag("Ajouter") %>
<% end %>

app/views/exemple_template/index_post_5.html.erb
<%= link_to 'documentation des formulaires', 'https://guides.rubyonrails.org/form_helpers.html', target: '_BLANK' %>
<br />

<%= @joueur.errors.full_messages %>

<!-- Chaque requête est sans mémoire, on doit lui redonner les valeurs qui ont été entré dans le html de réponse même s'il contient des erreurs -->
<%= form_with(url: "/exemple_template_post_5", method: "post") do %>
  <%= label_tag(:nom, "nom:") %>
  <br />
  <!-- https://guides.rubyonrails.org/form_helpers.html#helpers-for-generating-form-elements -->
  <%= text_field_tag(:nom, @joueur.nom) %>
  <br />
  <%= label_tag(:prenom, "prenom:") %>
  <br />
  <%= text_field_tag(:prenom, @joueur.prenom) %>
  <br/>
  <%= label_tag(:email, "email:") %>
  <br/>
  <%= email_field_tag(:email, @joueur.email) %>
  <br />
  <%= submit_tag("Ajouter") %>
<% end %>